### ISSUE TITLE
Refactor SignallingWebServer to be consumable as an extensible libarary

### ISSUE THREAD

**Issue by DenisTensorWorks** [EpicGames/PixelStreamingInfrastructure#1]
We want to update the SignallingWebServer scripts so they can be interfaced with as a library.

This will more easily allow users to simply integrate the functionality they need from the library into their own infrastructure, along with the benefits described in the referred to issue above.

---

Moved from https://github.com/EpicGames/PixelStreamingInfrastructure/issues/10

**Comment by lukehb** [comment]
Behold: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/blob/master/README.md#npm-packages
