### ISSUE TITLE
How do we use https for the signalling server?

### ISSUE THREAD

**Issue by bakermanbrian** [EpicGames/PixelStreamingInfrastructure#121]
## Component your question relates to
- [ ] Signalling server

The matchmaker has clear documentation on using https, but I can't seem to figure out how to do it for the signalling server with a turn server. Any guidance?

**Comment by lukehb** [comment]
It depends what branch of the PSInfra you are using, for `5.5` you can start the server with `-https` as outline on this page: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/tree/master/SignallingWebServer

If you are on previous version you can add `"UseHTTPS": true` to this [config.json file](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/blob/UE5.4/SignallingWebServer/config.json)

Feel free to reopen this if this is not enough info.

**Comment by bakermanbrian** [comment]
Sorry for my lack of specificity -- do I need to provide a client-key.pem and client-cert.pem for https to work? If so, which directory does this load from?

**Comment by lukehb** [comment]
> do I need to provide a client-key.pem and client-cert.pem for https to work?

Yes.

>  If so, which directory does this load from?

If you are using version pre 5.5 it will load them from `certificates` subdirectory next to `config.json`.

These docs show some visual steps for how one might create some self signed certificates for testing with PS: https://dev.epicgames.com/documentation/en-us/unreal-engine/experimental-pixel-streaming-features#creatingtherequiredcertificates

In 5.5 and newer ([docs link](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/tree/master/SignallingWebServer)) they are specified as follows:

```
 --ssl_key_path <path>             Sets the path for the SSL key file. (default: "ssl/key.pem")
  --ssl_cert_path <path>            Sets the path for the SSL certificate file. (default: "ssl/cert.pem")
```
