### ISSUE TITLE
Can I use 5.3 pixel streaming branch for a 5.4 project?

### ISSUE THREAD

**Issue by bakermanbrian** [EpicGames/PixelStreamingInfrastructure#133]
Same as title -- is it possible to use 5.3 pixel streaming branch for a project I created with 5.4?

**Comment by DenisTensorWorks** [comment]
Hi @bakermanbrian. We do not recommend using mismatching versions of the Pixel Streaming infrastructure and UE projects as
there can be breaking changes between versions. We do not cross-test versions of UE against different versions of PS Infra, so we have no information about their compatibility.

If you do decide to run the 5.3 infrastructure on a 5.4 project, it will likely work to an extent, but you might encounter performance or functionality issues.
