### ISSUE TITLE
[BUG] - VR headsets unable to connect to master branch of infra

### ISSUE THREAD

**Issue by MWillWallT** [EpicGames/PixelStreamingInfrastructure#140]
**UE Version:**
UE 5.5

**Frontend Version:**
Master

**Problem component**
Signalling Server + VR

**Description**
At the current stage, VR headsets are unable to connect to a local machine running the latest version of the infrastructure. Comparison test done with 5.3 infra and it's succeeded immediately. 
Test was done on Quest 2 and Quest 3 headsets.

**Steps to Reproduce:**
1.Setup basic Pixel Streaming VR project
2.Setup master branch infra with basic https certificates + start stream
3.In your desired headset on the same wifi network, open the headset browser and connect to the signalling PC IP address.
4. Note failure

**Expected behavior**
VR headset browser should be able to connect to a local network signalling server without fail

**Platform (please complete the following information):**
 - OS: Windows + Quest 3
 - Browser: Meta Browser

**Comment by lukehb** [comment]
Fixed in: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/pull/177
