### ISSUE TITLE
[BUG] - Unable to locate player.html

### ISSUE THREAD

**Issue by PhiKuz** [EpicGames/PixelStreamingInfrastructure#141]
**UE Version:**
UE 5.4.2

**Frontend Version:**
UE5.4-1.0.1

**Problem component**
Signalling Server, Frontend

**Description**
The signalling server cannot locate player.html out of the box, despite locating the proper http_root directory.

**Steps to Reproduce:**
1. Extract PixelStreamingInfrastructure-UE5.4-1.0.1.zip
2. Run setup.bat
3. Run start.bat
4. Connect to localhost through Chrome

**Expected behavior**
The previous version that was made for 5.3 was able to locate player.html or any other .html I specified in the config.

**Screenshots**
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/121882300/0553348a-fe41-4c4a-9f10-e528811c9134)
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/121882300/999cb8cd-6c62-409b-99d9-4d8f2872ed55)

**Comment by mcottontensor** [comment]
Looks like you're running the 5.5 branch of the infra? I tested your steps with the 5.4-1.0.1 release zip and it works fine. However there is no start.bat as it is still run_local.bat

**Comment by PhiKuz** [comment]
Getting the source .zip gave me the 5.5 branch. Getting the UE5.4-1.0.1.zip specifically should work. Just a user error.
