### ISSUE TITLE
RenderOffscreen on Linux  issue

### ISSUE THREAD

**Issue by PotatoMilks** [EpicGames/PixelStreamingInfrastructure#145]
## Component your question relates to
- [ ] Signalling server
- [ ] Frontend library
- [ ] Frontend UI library
- [ ] Matchmaker
- [ ] SFU
- [ ] This repo
- [x] Other

## Background
We develop on Windows11 and provide pixel streaming services on Linux servers.
Development environment: Windows 11, UE Engine 5.0.3 & UE Engine 5.4.1
Cross-compilation: v20_clang-13.0.1-centos7 (for UE 5.0.3) & v22_clang-16.0.6-centos7 (for UE 5.4.1)
Linux server: Centos 8, i9-12900KF, RTX3080, memory 128GB

## Question
1. When starting with  **-RenderOffscreen**  command，Server memory will increase significantly over time until the memory is full.
In Linux system, through the command: 
`./Fuzzy.sh -PixelStreamingURL="ws://127.0.0.1:13250" -PixelStreamingHideCursor -RenderOffScreen -ForceRes -ResX=1896 -ResY=800`
When running, the system's memory usage will continue to grow in a short period of time.
When the server is connected to the screen, run it through the command: 
`./Fuzzy.sh -PixelStreamingURL="ws://127.0.0.1:13250" -PixelStreamingHideCursor -ForceRes -ResX=1896 -ResY=800`
The memory will not change significantly.（ I connect the server to a monitor and start it through the graphical interface, without using **-RenderOffscreen**  command, the memory is normal.）

2. Note: In the production deployment environment, the project is generally started through SSH, and the server will not be equipped with a display. And through SSH, if the -RenderOffScreen command is not used, a display window will pop up on the client.

## Additional context
Operating system
![系统版本](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/82198331/e226d6e9-e620-44ac-885e-e2c6657d9c0f)
Graphics card and driver version
![驱动版本](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/82198331/a2566dca-0beb-4c72-b941-1f005a45660b)
启动命令
![启动命令](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/82198331/8003a8d9-ecef-4fd8-b48d-c3116f8a2084)
Memory problem
Satrt:
<img width="573" alt="Start" src="https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/82198331/0ecfb359-b9f8-407b-8705-72877c44028a">
Run for half an hour:
<img width="543" alt="End" src="https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/82198331/aeb27150-d187-4445-8be4-2a96bd5a3564">

**Comment by lukehb** [comment]
Hi,

As you are using 5.0.3 there have been a number of bug fixes around memory leaks since that version.

1. Would you be able to try a newer version of UE (such as 5.4.2) to confirm if the issue still exists in your setup?

2. Additionally, could you make a fresh third person project with Pixel Streaming enabled and check if you can reproduce the issue?

Regards, Luke.

**Comment by lcdlv** [comment]
Hi! I have the same issue, but for my surprise is not -RenderOffScreen. The problem is the linux package itself.
I create a thread in the forum: https://forums.unrealengine.com/t/first-person-template-on-ubuntu-consume-99-gpu-on-nvidia-t4/1958757

**Comment by lukehb** [comment]
@lcdlv to clarify, does your issue occur even without Pixel Streaming plugin?

**Comment by lcdlv** [comment]
Yes, with or without the plugin the problem persist. It's a much bigger problem than pixel streaming plugin. It's imposible launch 2 o 3 instance in this situation.

**Comment by lukehb** [comment]
Thanks, I've passed along your forum post to some folks at Epic 🤞
