### ISSUE TITLE
emitUIInteraction is not defined, ue 5.3.2

### ISSUE THREAD

**Issue by alzosmol** [EpicGames/PixelStreamingInfrastructure#150]
## Component your question relates to
- [ ] Signalling server
- [ ] Frontend library
- [ ] Frontend UI library

hi, i'm trying to recreate this: https://youtu.be/LKpDNmHO1Hk - in my case showcase.html includes a slider code and a custom slider.js with a function from his lesson, so browser's console shows both - category and item values like Object { Category: 1, Item: "84" } + i managed everything in bp in my app (bind event to on input & etc) but console says: "emitUIInteraction is not defined". please help me to figure out, is there some new restriction for this kind of interaction or i just need some extra setup for the newest javascript code? thanks in advance

**Comment by alzosmol** [comment]
![Screenshot_1](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/59736858/6100fb54-539c-4d5f-9cd0-d3be283a5b61)
![Screenshot_2](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/59736858/55fa67da-009f-4988-a44f-dec46359d911)
![Screenshot_3](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/59736858/62a0fde0-1698-40d1-87ac-653ecd4ca71f)

* if i play and change value on the slider there is no print string message

**Comment by lukehb** [comment]
Hi,

That tutorial appears to be out of date.


Please download the Pixel Streaming showcase from the Epic Games launcher and follow these steps to set it up fully:

[PS Showcase 5.3 docs](https://dev.epicgames.com/documentation/en-us/unreal-engine/pixel-streaming-sample-project-for-unreal-engine?application_version=5.3)

Once you have it set up you can modify the showcase.html and showcase.ts to add a slider and call emitUIIteraction, as shown here:

https://github.com/EpicGamesExt/PixelStreamingInfrastructure/blob/24890856667ef69d572481fe1b74ec5201d1bb27/Frontend/implementations/typescript/src/showcase.ts#L82

Regards, Luke.

**Comment by alzosmol** [comment]
hi Luke, thanks for the hint, i'll try this method. so i'll need to rebuild the ui-library after making changes, like this, right?

ui-library>npm run build
platform_scripts\cmd>build.bat --build

**Comment by lukehb** [comment]
Yeah exactly, you can also do `run_local.bat --build` if you prefer to do it all one go.

**Comment by lukehb** [comment]
I'm going to close this one out.
