### ISSUE TITLE
[BUG] - Connection issue on LAN in network restricted environment

### ISSUE THREAD

**Issue by luming222** [EpicGames/PixelStreamingInfrastructure#157]
**UE Version:**
E.g. UE 5.1.1

**Frontend Version:**
E.g. UE5.3-0.3.0

**Problem component**
E.g. Signalling Server, Frontend, Pixel Streaming C++ plugin

**Description**
WEBRTC CONNECTION NECOTIATED  
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/171756926/48e5d732-d2a9-42b4-8d92-977944e20f01)

**Steps to Reproduce:**
1. The environment is configured as a back-end computer to deploy the UE5 push service. The front-end machine obtains the UE5 push service, but the overall process is deployed on the LAN, and the front-end machine is not connected to the public network
2. After I open the pixel stream service at the back end, the front end has already received it, but it will be stuck in the "WEBRTC CONNECTION NEGOTIATED" page. When I open the front-end developer tool, I initially find that several front-end pages are missing, like font libraries. Later I think the network administrator has applied for access to 'fonts.gooleapis.com','fonts.gstatis.com' but there is a new problem later, fonts is obtained but seems to be of no use
3. I would like to ask if the front-end browser needs to request external resources of the public network when it is displayed, because it is deployed in the internal network, the front-end machine may intelligently access specific urls to obtain resources, and whether these urls can be explained
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/171756926/f9d66d48-32d0-408c-99b0-4b9bcf4f5fa3)

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**

**Additional context**

**Comment by lukehb** [comment]
And does this occur is you use the latest version of PixelStreamingInfrastructure repository from master branch too?

**Comment by lukehb** [comment]
Can you attach a larger version of the first screenshot? The resolution is too low to read it clearly.

**Comment by luming222** [comment]
> 你能附上第一个屏幕截图的更大版本吗？分辨率太低，无法清晰阅读。

![u1](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/171756926/a4bf162c-ed23-4d62-b44c-5561ff08e566)

**Comment by luming222** [comment]
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/171756926/f8d61ed2-7e1b-464b-a3e5-b36f8b604cc2)

**Comment by lukehb** [comment]
Okay thanks!

Yes, as I said before, can you try using the latest version of PixelStreamingInfrastructure repository from master branch too to see if the problem happens there too?

**Comment by luming222** [comment]
@lukehb 
I have opened the network of the front-end machine, but in this case, can you ask what network ports need to be opened if the back-end UE5 is the server? I wonder if it is because the network ports are not fully opened

**Comment by lukehb** [comment]
This is not a ports issue. It looks to be a failure in the JavaScript side. I note you are using mismatched versions of UE and frontend (UE 5.1.1) and 5.3-0.3.0 for the frontend, this is not recommended. I am trying to determine if a newer frontend version will fix this for you. If it does not, I would also ask you to try the frontend version for 5.1.

**Comment by luming222** [comment]
@lukehb Thank you for remembering now that my UE5 is version 5.1, but the signaling server is displayed above 5.2, but there is no problem in my local LAN test. Now this problem occurs when I deploy the test environment, so I always suspected that it was a network problem. I will now try to pull the master branch for operation if you can solve the problem I would be very gratefu

**Comment by lukehb** [comment]
Please match all three components: signalling server, UE, and frontend to the same version if possible. If not possible, please try the latest signalling server and frontend from master.

**Comment by luming222** [comment]
@lukehb Excuse me, I found out that my pixel stream is the result of the packaging of the UE5 plugin, but it works on my local LAN, but it does not work in the test environment. I feel that it is not a version mismatch problem. It may be that the relevant front-end library is not linked to，Because there was a guy who had the same problem before but he solved the problem after connecting to a library and I tried to contact him to solve it

**Comment by lukehb** [comment]
Okay if all components are a result of packaging that should be fine. 

Next things to try is in the case where it does not connect could you open chrome://webrtc-internals and share the ICE candidate grid that is displayed. This should tell us if there is a network connectivity issue or not.

**Comment by luming222** [comment]
> Okay if all components are a result of packaging that should be fine.
> 
> Next things to try is in the case where it does not connect could you open chrome://webrtc-internals and share the ICE candidate grid that is displayed. This should tell us if there is a network connectivity issue or not.

@lukehb 
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/171756926/b7eb5ff8-777f-459f-a7b1-02494d8ff590)There seems to be a problem here

**Comment by lukehb** [comment]
Okay, yes, there does seem to be a network connectivity issue between the two machines.

WebRTC will try to open a UDP connection on a random port between 49152 and 65535. This is not configurable in UE 5.1, if you upgrade to UE 5.4 it can be configured though.

Windows firewall can also block the incoming/outgoing connections on the browser/UE side so you may wish to disable that or add an exception.

**Comment by luming222** [comment]
@lukehbHello, I am still waiting for the administrator to enable the UDP related port on my UE5 machine. However, I tested it on my own local LAN and found that there seems to be no development of the UDP related port on UE5

**Comment by lukehb** [comment]
You can verify the connection type by starting Pixel Streaming and connecting and then going to chrome://webrtc-internals and expanding the ICE candidate grid and looking for the connected candidate pair. You will note the column called "protocol/candidate type".


This table will show you the transport protocol used (e.g. TCP/UDP) and the ports used on both sides.

HOST candidate means a connection using your local addresses (which is what you would expect over LAN).

![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/1215582/c0ed1b00-3f12-45d2-8ec2-3ff174f3463d)

**Comment by luming222** [comment]
@lukehb ![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/171756926/b42ca442-9eec-4b93-8daa-ae02cbc302fd)我的显示是这样

**Comment by luming222** [comment]
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/171756926/b15a6ca0-0afe-482d-8d46-83a823c84bcf)
My display is as shown in the picture
@lukehb

**Comment by lukehb** [comment]
The above image is between the two machines that do not successfully connect, correct? As you can see it is trying to perform a connection on the local machine (browser) on UDP port 9 and then in next candidate pair on 49893. As I mentioned above, you will have to get your network admin to open UDP ports in the range 49152-65535.

If you would like, you can also check the ICE candidate grid from the case where a successful connection is made (e.g. all running on the same machine) and you can note the transport protocol and ports used in a successful connection case.

**Comment by luming222** [comment]
@lukehb Is it the UDP port of the machine where UE5 is deployed？

**Comment by lukehb** [comment]
In the table above the:

- "local-candidate" are addresses and ports it is trying on the web browser (e.g. in the image above UDP port 9)
- "remote-candidate" are addresses and ports it is trying on the UE machine (e.g. in the image above UDP port 56747)

**Comment by lukehb** [comment]
Both sides need UDP ports accessible for inbound and outbound UDP traffic.

**Comment by luming222** [comment]
@lukehb I'm sorry to bother you for so long. Since I've just been in contact with this, I still don't quite understand. Is it because the port over there is not open, as shown in the picture? Is it because neither side of the machine is open or one is not open
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/171756926/b20eb916-e08b-4887-b678-78acf00be4ca)
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/171756926/e788aaed-6e51-4f31-8465-56ec8da6af3f)
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/171756926/3d581079-d1ab-4176-a63b-4a3a372d0dbe)

**Comment by lukehb** [comment]
>  Is it because the port over there is not open?

> Is it because neither side of the machine is open?

> or one is not open?

I can't know the answer to any of those from my side and neither can WebRTC. Only you (or your network adminstrator) can tell if you have the UDP ports open or not.

I can tell you in order to connect both your local machine and the UE machine must allow inbound and outbound traffic on UDP ports in the range 49152-65535.

**Comment by luming222** [comment]
@lukehb ![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/171756926/34218861-87b6-4f86-9b31-04421049e8a2) 
I switched to version 5.1 signaling and related content

**Comment by luming222** [comment]
@lukehb 
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/171756926/99c03ac3-119a-463e-848e-d3a544c4385f)
He's much better now than before

**Comment by luming222** [comment]
@lukehb 
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/171756926/f05e2f99-1bb5-4f12-a151-f7f5202b8146)
Now the network is connected, the right is my local test, it's normal, the left is abnormal, there is no transmission, it seems that there are two missing data, I think maybe the problem will be here

**Comment by luming222** [comment]
@lukehb 
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/171756926/ffdc29f7-a5dd-4362-9a03-19318a4cfea1)
 I'm sorry that the last message was sent incorrectly The left is correct, and the right is the machine that cannot be displayed

**Comment by lukehb** [comment]
Unfortunately those screenshots do not have any useful information in them (the ICE candidate grid that I showed you above it more useful for debugging network connectivity). Have you (or your network admin) opened the ports I mentioned?

**Comment by luming222** [comment]
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/171756926/1657b4b8-b612-44d4-acb0-8f7a0235a230)
I think I may have found the problem, but it's a bit strange because during the local testing, there was no TCP involved. Now I realize that the TCP port is not open, and my understanding is correct. Is the pixel flow possible to be useful in the entire ICE process during webrtc sdp negotiation? TCP

**Comment by luming222** [comment]
@lukehb

**Comment by lukehb** [comment]
TCP being closed should be okay. WebRTC _can_ use TCP in some browsers, but it is not the recommended way as transmission is much slower in congestion or case of packet loss. Having only the UDP ports open should be acceptable.
