### ISSUE TITLE
[BUG] - Error: Selected codec was not a supported codec, falling back to negotiating codecs…

### ISSUE THREAD

**Issue by KonstantinosLeriou01** [EpicGames/PixelStreamingInfrastructure#159]
**UE Version:**
UE 5.3.0

**Frontend Version:**
Latest React

**Problem component**
Signalling Server, Frontend

**Description**
Error: Selected codec was not a supported codec, falling back to negotiating codecs…
So i am connecting to the signalling server from another frontend server. While i can connect  and everything seems good, every 60s its disconnecting with code 1006 and in the webconsole i am getting DOMException: Failed to execute 'setCodecPreferences' on 'RTCRtpTransceiver': Invalid codec preferences: invalid codec with name "H264", and its connecting back. I have tested connecting to the signalling server without a frontend server and i have no errors and no disconnects but this only happens when i am connected to the signalling server from another frontend server. I am using the react module

**Expected behavior**
Connect from the frontend server to the signalling server without disconnecting for 1s and reconnecting back 

**Platform (please complete the following information):**
 - OS: Linux
 - Browser: chrome

**Comment by mcottontensor** [comment]
This sounds strange to me. Am I correct in my understanding that you are running the signalling server on one server and the frontend is hosted on another server that is pointing to the signalling server?

It's not a usual setup but it should be fine. What's interesting to me is that it works fine (I assume you mean it's streaming fine and you can see the video) and then suddenly stops.

It sounds like to me that the connection between the streamer and the frontend is actually being force closed after some time and that the `setCodecPreferences` error might actually be a side effect of the connection being closed.

Can you verify that the streamer is working fine and there are no errors or log messages relating to disconnections? Can you try the same streamer and try to run the typescript frontend on the signalling server and see if you get the same behaviour?

If you could provide actual logs of each component too, that might help us diagnose what's going on.

**Comment by KonstantinosLeriou01** [comment]
I can confirm that using only the signalling server webserver no error at all. There seems likely a problem from my frontend server itself. It seems i am not using the latest react thing. I will try use typescript in the frontend server just for the test. I will keep you informed. Thanks!!
