### ISSUE TITLE
Right Eye Only Has 1/3 and Really Bad Resolution

### ISSUE THREAD

**Issue by DenisTensorWorks** [EpicGames/PixelStreamingInfrastructure#16]
Originally opened by [@ffreality](https://github.com/ffreality)

**UE Version:**
5.3.1 Epic Launcher Version

**Frontend Version:**
Both Master and Release UE5.3-1.0.1

**Description**
When I enable PixelStreaming, right eye is not completely black but I can see only 1/3 of right eye on both Unreal Editor and Meta Quest Browser (Immersive WebVR View).

Resolution is really bad.

**Steps to Reproduce:**
1.  I did `Pixel Streaming in Virtual Reality` steps from
https://docs.unrealengine.com/5.3/en-US/experimental-pixel-streaming-features/

2. I am not using VRTemplate and its Pawn. I have a PlayerCharacter which I use all on my other projects. 
I deleted all of OpenXR related functions. Right now it has only Motion Controller Components, VRCameraRoot and VRCamera.

3- I also try VRTemplate to just test it.

4- I disabled Instance Stereo Render, Mobile HDR, Forward Rendering.

**Expected behavior**
1- An acceptable resolution (not same level with Quest Link but better than current)
2- I can see both eye at the same time

**Screenshots**
![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/10528447/7be67159-16d7-4a84-ab10-15db8b183015)

**Platform (please complete the following information):**
 - OS: Windows 11 Pro
 - Meta Quest Browser (Latest Updates Installed)
 - Oculus Quest Pro with Latest Updates

**Additional context**
My notebook is an Asus Rog which has AMD Ryzen 9 5900HX with APU and RTX 3080. It doesn't have complete APU disable feature on Asus Armory Crate. Quest Link doesn't have problem with it but can this be related with APU ?

For resolution, I have 16Gbit WiFi 6E Router. Quest Pro connected to 6GHZ 6E channel and my notebook 5 GHZ WiFi 6 Channel. So, It shouldn't be a network problem.

---

Moved from https://github.com/EpicGames/PixelStreamingInfrastructure/issues/462

**Comment by DenisTensorWorks** [comment]
This has been fixed in 5.4.

**Comment by DevarthSambare** [comment]
hey still not fixed in 5.4 i am still getting the issue
