### ISSUE TITLE
Problem of frontend in IOS

### ISSUE THREAD

**Issue by xiyouZ** [EpicGames/PixelStreamingInfrastructure#165]
## Component your question relates to
- [x] Frontend library
- [x] Frontend UI library

## Background
When using the TypeScript frontend UI to connect to the Signalling WebServer, it works normally on desktop devices, but when accessed on iOS mobile devices, full-screen mode and streaming functionality are unavailable.

## Question
I understand the issue is related to iOS, but I'm unsure how to resolve it correctly. Please advise on the appropriate fix. Thank you.

**Comment by mcottontensor** [comment]
We just pushed a change (#214) to master, 5.3 and 5.4 branches that might have solved this for you. If you could pull the changes an try again and let me know that would be helpful. Thanks.
