### ISSUE TITLE
[BUG] - Video element showing  edit text

### ISSUE THREAD

**Issue by adityayaduvanshi** [EpicGames/PixelStreamingInfrastructure#171]
**UE Version:**
E.g. UE 5.1.1

**Frontend Version:**
E.g. UE5.2-0.3.0

**Problem component**
Video element showing edit text.

**Description**
I implemented the pixel stream in react js. its  working fine but in the  mobile  view it shows this message. 
![WhatsApp Image 2024-06-04 at 1 56 51 PM](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/38696088/416942f1-0d7e-42d7-91db-ecfab0dd24ec)

**Comment by adityayaduvanshi** [comment]
Any help?

**Comment by mcottontensor** [comment]
Should be fixed with the latest change in master from #238
