### ISSUE TITLE
[BUG] - Turn Signalling Server Session Closes By Itself Automatically

### ISSUE THREAD

**Issue by yoponchik** [EpicGames/PixelStreamingInfrastructure#201]
**UE Version:**
UE 5.3.2

**Frontend Version:**
UE5.3-0.3.0

**Problem component**
Signalling Server

**Description**
When I run `Start_WithTURN_SignallingServer.ps1`, two windows pop up. One runs `node.exe` and the other `turnserver.exe`. But the window with `node.exe` closes by itself and ends the signalling server session.

**Steps to Reproduce:**
1. In `config.json`, change  the `UseHTTPS` to `true` in `.\PixelStreamingInfrastructure\SignallingWebServer`
2. Run `Start_WithTURN_SignallingServer.ps1`

**Expected behavior**
1. I expect the two windows to remain open. The window running `node.exe` must have an output `Http listening on *: 80`

**Screenshots**
- No Screenshots
    - Closes too fast
- No Logs

**Platform (please complete the following information):**
 - OS: Windows 11
 - PixelStreamingInfrastructure from UE5.3 branch

**Additional context**
- None

**Comment by lukehb** [comment]
@MWillWallT When you get a chance can attempt this repro? (Note version UE5.3-0.3.0 of the frontend)

**Comment by mcottontensor** [comment]
If it's closing by itself it's most likely a configuration issue. If you could run the signalling server in a powershell prompt without using the WithTURN script it should allow you to see what is causing it to close. Does `Start_SignallingServer.ps1` give you the same result?
