### ISSUE TITLE
How can I force close peer connection/data channel?

### ISSUE THREAD

**Issue by bakermanbrian** [EpicGames/PixelStreamingInfrastructure#202]
## Component your question relates to
- [x] Signalling server
- [x] Frontend library
- [ ] Frontend UI library
- [ ] Matchmaker
- [ ] SFU
- [x] This repo
- [x] Other

## Question
I have figured out how to force close WebRTC connections server-side and require that user to send an updated auth token to reconnect. However, how can I force close an existing peer connection/data channel, not from the frontend?

**Comment by lukehb** [comment]
On the signalling server side you could terminate the websocket connect - that will trigger it to close. Is that workable in your case?

**Comment by lukehb** [comment]
There is also the `kick` blueprints that can do this from the UE side.

While these are deprecated in UE 5.4 the plan is to bring them back.

If you are using 5.4:

![image](https://github.com/user-attachments/assets/f02f0638-cdd8-4ca6-83a2-a0fb122c2915)
![image](https://github.com/user-attachments/assets/685c89d3-e90d-4fce-8ba6-0313d3cf7f5f)
