### ISSUE TITLE
Game UI Occluded by Navigation Bar on Mobile

### ISSUE THREAD

**Issue by lcdlv** [EpicGames/PixelStreamingInfrastructure#203]
## Component your question relates to
- [ ] Signalling server
- [x ] Frontend library
- [ ] Frontend UI library
- [ ] Matchmaker
- [ ] SFU
- [ ] This repo
- [ ] Other

## Background
My game UI is Occluded by navigation bar on Mobile.

## Question
How can I adjust the player to fill the mobile screen and prevent UI overlay?

Here's an example:

This is on Windows:
![Screenshot_1](https://github.com/user-attachments/assets/d4b01c71-d822-4e5c-aea5-b365d99b0718)

This is on Mobile:
![Screenshot_2](https://github.com/user-attachments/assets/e4596dff-c30a-48e6-a455-350e3d382068)

**Comment by lukehb** [comment]
What if you enable the match viewport resolution option in the frontend?

**Comment by lcdlv** [comment]
Hi @lukehb ! It's enabled right now. I'm using Signalling Server for Unreal 5.3.
I'm not specialist in web development, so I need you point me where to touch to change that behaviour.

**Comment by lukehb** [comment]
Try changing in `https://github.com/EpicGamesExt/PixelStreamingInfrastructure/blob/master/Frontend/implementations/typescript/src/player.html`

`height: 100vh;` to `height: 100dvh;` (note the `d`)

Which should dynamically account for top and bottom on device nav showing: https://developer.mozilla.org/en-US/docs/Web/CSS/length#dynamic

If it works let me know and I will push this live.

**Comment by lcdlv** [comment]
HI @lukehb !! That's works!!!
Thanks!!

![Screenshot_1](https://github.com/user-attachments/assets/27104341-1721-4772-986e-765779adfbf0)
