### ISSUE TITLE
[BUG] - Video freeze on chome ipad after exiting fullscreen

### ISSUE THREAD

**Issue by aussiedwarf** [EpicGames/PixelStreamingInfrastructure#219]
**UE Version:**
E.g. UE master

**Frontend Version:**
E.g. UE5.5 and master

**Problem component**
Frontend

**Description**
After connecting to a stream in Chrome on iPad Pro, going fullscreen, then out of fullscreen, the video is frozen.

Information still shows frames are being decoded.

**Steps to Reproduce:**
1. Start pixel streaming and start a stream.
2. Open chrome on ipad, connect to the stream, click to start.
3. Press the fullscreen button.\
4. Attempt to move the view by touch dragging.
5. Exit fullscreen (should be able to do this by dragging.
6. Notice the video is now frozen.

**Expected behavior**
1. After exiting fullscreen, the video stream should still be running

**Platform (please complete the following information):**
 - iPad Pro
 - OS: iPadOs 17.5.1
 - Chrome
Tested in Safari and the issue is not reproducable there.

**Additional context**
Problem may be because in fullscreen, touch dragging is pausing the video stream.

**Comment by lukehb** [comment]
This is the behaviour of Chrome/Firefox on iPad, YouTube does the same. Dragging around in fullscreen on Chrome + iPad always make the video minimise/pause too. I think the best solution is to disable fullscreen in Chrome + iPad?

wdyt @aussiedwarf
