### ISSUE TITLE
[BUG] - All linux compiled projects run at 99% of GPU on AWS Instance with T4/T5.

### ISSUE THREAD

**Issue by lcdlv** [EpicGames/PixelStreamingInfrastructure#226]
**UE Version:**
UE 5.4.3

**Frontend Version:**
UE5.4

**Problem component**
My game was working on 99% of GPU in my AWS instance (g4dn.xlarge) in Ubuntu Server 22.04.

**Description**
My game was working on 99% of GPU in my AWS instance (g4dn.xlarge) in Ubuntu Server 22.04. My idea is lauch 2 o 3 instances for pixel streaming, but now I can launch only one because is eating all the GPU.
To check if was my game or all games, I exported a First person template and fails too. I check usean crossplatform compile, and with Ubuntu native compile.
I create a thread in the forum: https://forums.unrealengine.com/t/first-person-template-on-ubuntu-consume-99-gpu-on-nvidia-t4/1958757

I know this is not a problem related with Pixel Streaming, but is very important for who use Pixel streaming and want to save son bucks using Linux operating systems.

**Steps to Reproduce:**
1. Launch Unreal Editor on Ubuntu 22.04
2. Create a First Person template.
3. Package.
4. The game takes the 99% of GPU.

**Expected behavior**
1. The game takes what the game takes in windows (in my case, 11%).

**Screenshots**
![Screenshot_1](https://github.com/user-attachments/assets/98f83c3d-8caa-4459-bb23-07fa7f44df5e)

**Platform (please complete the following information):**
 - AWS Instance g4dn.xlarge
 - Ubuntu 22.04
 - Unreal Editor 5.4.3

**Additional context**

**Comment by MWillWallT** [comment]
Hi there!

Thank you for sharing the issue and providing such helpful reproduction steps.

Given that this issue does not pertain to Pixel Streaming, we'll close the issue. However we have reached out to the Epic internal team to investigate the issue and should hopefully have it nailed down soon. We know this does also impact Pixel Streaming as a whole so keep an eye out.

**Comment by lukehb** [comment]
Updated forum post with a few questions :)
