### ISSUE TITLE
Make frontend changes to accomodate min/max encoder quality changes in 5.5

### ISSUE THREAD

**Issue by DenisTensorWorks** [EpicGames/PixelStreamingInfrastructure#234]
**Component your feature request relates to**
- [x] Frontend library
- [x] Frontend UI library

**Problem your feature solves? Please describe.**
We need to accomodate for the move to min/max encoder quality scale instead of min/max QP cvars. 
Ensure we still send the old MinQP/MaxQP messages for backwards compatibility.

Internal reference: UE-220968

**Comment by lukehb** [comment]
@mcottontensor When you get round to this, let's have a discussion. But basically some internal discussion of changing these on the plugin side, which has some flow on effect to the frontend.
