### ISSUE TITLE
How to run/scale multiple Pixel Streaming sessions from one signalling server?

### ISSUE THREAD

**Issue by shrenik2703** [EpicGames/PixelStreamingInfrastructure#236]
Hi Team,

I've noticed that in this repository, you've provided a Docker file to run the signaling server in a separate container. However, based on my understanding, if you want each user to have a unique controllable session, you would need to spin up a separate signaling server for each session. So why not include the signaling server and the Unreal Engine packaged project within a single image? Is there a workaround for this?

When I dug deeper into the scalable pixel streaming architecture, I noticed that you are providing unique controllable sessions via a single signaling server. Could you explain how this is achieved?

**Comment by lukehb** [comment]
Hi,

I'll address a few things here.

> if you want each user to have a unique controllable session, you would need to spin up a separate signaling server for each session

This is actually not the case. One signalling server can support `N` Pixel Streaming sessions. Each Unreal Engine session simply has to identify with a unique identifier, which can be done by using `-PixelStreamingID='

> So why not include the signaling server and the Unreal Engine packaged project within a single image? Is there a workaround for this?

For best scaling the signalling server, web server, and Unreal Engine instance should all be run in their own containers or similar.

Hope that helps answer that!

Regards, Luke.
