### ISSUE TITLE
[BUG] - ReferenceError: getUniqueLegacyId is not defined

### ISSUE THREAD

**Issue by ghost** [EpicGames/PixelStreamingInfrastructure#242]
**UE Version:**
UE 5.4

**Frontend & Signalling Server Version:**
UE5.3

**Problem component**
Signalling Server error after OS restart

```server-config1-error.log
/home/ubuntu/ProjectName/Linux/ProjectName/Samples/PixelStreaming/WebServers/SignallingWebServer/cirrus.js:532
                const newLegacyId = getUniqueLegacyId();
                                    ^

ReferenceError: getUniqueLegacyId is not defined
    at Timeout._onTimeout (/home/ubuntu/ProjectName/Linux/ProjectName/Samples/PixelStreaming/WebServers/SignallingWebServer/cirrus.js:532:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

**Description**
We have configured the signalling server as a service like this

```service
[Unit]
Description=Server config1 Service
After=network.target

[Service]
Type=simple
ExecStartPre=/bin/sleep 2
ExecStart=/home/ubuntu/ProjectName/Linux/ProjectName/Samples/PixelStreaming/WebServers/SignallingWebServer/platform_scripts/bash/Start_WithTURN_SignallingServer.sh --configFile config1.json
User=ubuntu
Group=ubuntu
Restart=on-failure
StandardOutput=append:/home/ubuntu/ProjectName/logs/server-config1.log
StandardError=append:/home/ubuntu/ProjectName/logs/server-config1-error.log

[Install]
WantedBy=multi-user.target
```

**Steps to Reproduce:**
1. Launch EC2 instance with Game & Signalling Server service
2. Tail the logs for signalling server error

**Expected behavior**
1. Signalling server ready to be redirected from frontend Matchmaker

**Platform (please complete the following information):**
 - OS: Ubuntu 22.04 LTS for Server
 - Firefox v129.0.1

**Additional context**
Restarting the service via `systemctl restart server-config1` works

**Comment by mcottontensor** [comment]
If you update your signalling server this should be fixed.

**Comment by ghost** [comment]
Thank you, its fixed!
