### ISSUE TITLE
Can not modify the UI 

### ISSUE THREAD

**Issue by mosheFuks** [EpicGames/PixelStreamingInfrastructure#245]
## Component your question relates to
- [ ] Frontend library
- [ ] Frontend UI library

## Background
I am attempting to modify the initial UI that appears when running Pixel Streaming from my local host. However, when trying to make any changes, such as replacing "Click to start" with "Click to Play," I am unable to locate the referenced file. The documentation is not very clear in this regard.

## Question
1. Where can I find this file, and how can I modify it?
2. Do I need to perform any preliminary installations?

**Comment by mcottontensor** [comment]
The "Click to start" text is set in the ui-library in src/Overlay/ConnectOverlay.ts
Most of the UI is created in this library and after changing the source you will need to rebuild the UI by either supplying the `--build` parameter to the platform script or by invoking webpack manually in some way.
