### ISSUE TITLE
Load Balancer on AWS

### ISSUE THREAD

**Issue by lcdlv** [EpicGames/PixelStreamingInfrastructure#246]
## Component your question relates to
- [ ] Signalling server
- [ ] Frontend library
- [ ] Frontend UI library
- [ ] Matchmaker
- [ ] SFU
- [ ] This repo
- [X] Other

## Background
Hi! I'm an Unreal Engine programmer with limited experience in TypeScript, JavaScript, etc. We are developing a custom scaling system for our multiplayer game in AWS using a load balancer. The challenge is that the load balancer needs to know whether an instance is in use or not. We are using one instance per signaling server + Unreal Engine game, with only one player accessing each instance.

## Question
How can we obtain data (using the AWS load balancer) to inform it when to launch a new instance or terminate an idle one? What approach do you use to manage this process?

**Comment by mcottontensor** [comment]
In the upcoming release of 5.5 we have added a REST API that can be enabled that will allow you to query streamers and players connected to a particular signalling server. Would that be what you are looking for?
You can see this API in the 5.5 branch [here](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/tree/UE5.5/SignallingWebServer)
