### ISSUE TITLE
[BUG] - Scrolling on iOS impossible if TouchInput enabled

### ISSUE THREAD

**Issue by gittaa** [EpicGames/PixelStreamingInfrastructure#264]
**UE Version:**
UE 5.4.3

**Frontend Version:**
UE5.4

**Problem component**
Frontend

**Description**
Scrolling is not working if touch input is enabled.

**Steps to Reproduce:**
1. Create a pixel streaming frontend with touch input enabled and some additional content that enforces scrolling
2. Try scrolling on a touch device, especially iOS

**Expected behavior**
1. Scrolling should work.

**Platform:**
 - OS: iOS, iPadOS
 - Safari
 - 15, 16, 17

**Comment by gittaa** [comment]
#229 and #259 might be related.

**Comment by mcottontensor** [comment]
There was a recent change #271 that might address this issue. If you could try with that latest change and let me know how it goes that would be super helpful. Cheers.

**Comment by gittaa** [comment]
Explicitly setting `FakeMouseWithTouches` to `false` should emulate #271, right? If so, it sadly won't change the scrolling bug.

**Comment by mcottontensor** [comment]
It should replicate it, yes.
When you say scrolling, do you mean scrolling on the frontend web or scrolling in the UE application side? What did you disable to make it work again?

**Comment by gittaa** [comment]
It turned out it was a bug in our code :|

Sorry for any inconvenience caused and thank you for your great work and commitment!
