### ISSUE TITLE
Multiples Streaming

### ISSUE THREAD

**Issue by luhhiiz** [EpicGames/PixelStreamingInfrastructure#280]
Multiples Streaming
- [x] Signalling server

## Background
Hi, I'm developing a project where I need to run 10 instances of pixel streaming, but lately in version 5.3 of Unreal I've noticed that it crashes a lot when running more than 3 simultaneous instances.

## Question
1.  Can anyone suggest any optimizations I can do in pixel streaming, or something like that?

Note: My machine is super powerful and so is my internet connection, so it's not the problem based on several tests I've done, but of course if anyone has any new ideas I'd like to try.

**Comment by mcottontensor** [comment]
When you say multiple instances, are you talking multiple streamers in the one Unreal project? Or running many copies of the Unreal application?
Can you provide any details on the crash reports? Stack traces etc.?

**Comment by luhhiiz** [comment]
Multiple streams in an unreal project, but each project is running on a specific local port, example: 

1st Instance -PixelstreamingPort=15000 -SFU=8888 
2nd Instance -PixelstreamingPort=15001 -SFU=8889 

 We currently use 3 instances, but our goal is to use 10 at least, but above 3 streams, even though it is a different Unreal project, it starts to cause a lot of lag, based on the tests we did, it has a very high latency, causing a crash that is impossible for the user to change.

**Comment by lukehb** [comment]
There was some fixes in that 5.4/5.5 that might help with that, does it happen there too?

Also, can you share a stack trace in a development build so we can see what the crash is?

**Comment by luhhiiz** [comment]
Hi, we are on 5.4 and the same thing happens, with more than 3 instances the streaming quality starts to lose and there is a very high delay.

Now about the tracking stack, how can I generate it? Through the usage log? I admit that I am still lost in Pixel Streaming.

**Comment by lukehb** [comment]
If you build in development with debug symbols, your log should contain the crash stack, if you could share that log here it might help.

Additionally, what CPU/GPU are you running on?

I am wondering if the first 3 streams are getting a hardware encoder (GPU encoding) then after that the subsequent streams are getting encoded using the CPU perhaps.

That would explain the slow down and subsequent crash potentially.

If you could share the details I asked for it might give some more insight for us. Thank you!
