### ISSUE TITLE
[BUG] - Connection issue on HTTPS

### ISSUE THREAD

**Issue by adityayaduvanshi** [EpicGames/PixelStreamingInfrastructure#29]
**UE Version:**
E.g. UE 5.1.1

**Frontend Version:**
E.g. UE5.3-0.3.0

**Problem component**
Connection failed in https in React Js library

**Description**
I am currently developing a web conference application using React.js and pixel streaming with the @epicgames-ps/lib-pixelstreamingfrontend-ue5.4 library. The application works flawlessly when running on localhost using HTTP, but encounters issues when attempting to connect via HTTPS.

**Steps to Reproduce:**
1. Run the application on localhost using HTTP.
2. Connect to pixel streaming and verify that it works as expected.
3. Update the application to use HTTPS.
4. Attempt to connect to pixel streaming, observe the issue.

**Code Snippet: **
`import { PixelStreamingWrapper } from './pixel-streaming-wrapper';

function PixelDom() {
  return (
    <div>
      <div style={{ overflow: 'hidden', height: '100%', width: '100%' }}>
        <PixelStreamingWrapper
          initialSettings={{
            AutoPlayVideo: true,
            AutoConnect: true,
            ss: 'wss://localhost:80',
            StartVideoMuted: true,
            HoveringMouse: true,
            WaitForStreamer: true,
          }}
        />
      </div>
    </div>
  );
}
`
`{
  "UseFrontend": false,
  "UseMatchmaker": false,
  "UseHTTPS": false,
  "UseAuthentication": false,
  "LogToFile": true,
  "LogVerbose": true,
  "HomepageFile": "index.html",
  "AdditionalRoutes": {},
  "EnableWebserver": true,
  "MatchmakerAddress": "localhost",
  "MatchmakerPort": "9999",
  "PublicIp": "localhost",
  "HttpPort": 81,
  "HttpsPort": 442,
  "StreamerPort": 8887,
  "SFUPort": 8881,
  "MaxPlayerCount": -1
}
`

**Additional context**
How can we start react js through pixel streaming

**Comment by yoponchik** [comment]
@adityayaduvanshi Having the same problem here: #201 .
Did you manage to fix it?

**Comment by adityayaduvanshi** [comment]
Yes i fixed it by upgrading the version
