### ISSUE TITLE
No Audio Streaming to browser with Pixel Streaming (AWS EC2 Instance)

### ISSUE THREAD

**Issue by varunshankar09** [EpicGames/PixelStreamingInfrastructure#296]
Background:
I am working on an AI digital human avatar project that is being streamed through Pixel Streaming TURN server hosted on an AWS EC2 instance. The stream is secured via HTTPS (using WSS for WebRTC) and accessed via a local browser using the EC2 public IP. The stream loads correctly, and interactions like button clicks, typing, and message sending works, but I face the following two issues:

1.	No Avatar Voice or Unreal Engine Audio in Browser:
When accessing the stream from a local browser, no audio (from the avatar or Unreal Engine) is played, despite being able to hear it in the Unreal Editor.
2.	No Audio Input from Browser Microphone:
The browser successfully requests and gains microphone permissions, but audio input is not transmitted back to the Unreal Engine instance. This issue occurs only when accessed from a local browser outside of the EC2 instance.

NOTE: Everything works as expected (both audio output and mic input) when streaming and interacting from a browser running directly on the EC2 instance itself but not on a browser outside of it.

Solutions and Checks Attempted:
1.	Added the PixelStreamingAudioComponent to the level in Unreal Engine.
2.	Verified that the browser has full permissions to use the microphone and speakers.
3.	Set Master and Master Submix as default for all audio settings in Unreal Engine.
4.	Chrome WebRTC logs confirm that Pixel Streaming WebRTC is actively transmitting audio, but no audio from the Unreal Engine is streamed to the local browser.
5.	Tried installing virtual audio devices like VB Cable and Voicemeeter on the EC2 instance to route audio, but this did not resolve the issue.

Question:
How can I ensure that:

1.  Audio from Unreal Engine (voice of the avatar and other sound) is streamed to the browser via Pixel Streaming?
2. Audio input from the browser’s microphone is successfully transmitted back to Unreal Engine in the EC2 environment?

I’ve reviewed the current documentation and attempted the common solutions, but I would appreciate any further insights into this issue.

Thank you for your help!

**Comment by lukehb** [comment]
Some things to check:

1. When you run this on a LAN with Pixel Streaming and signalling webserver, if you access you UE machine's local ip in the browser of another machine do you hear the audio on the other machine? (e.g. is this an AWS config issue or always no audio on the remote machine even if not on AWS).

2. Your audio is definitely played back in the UE submix? Some plugins/technologies like bink do not play back audio using the UE submix so Pixel Streaming cannot stream them.

Can you also provide UE version and EC2 instance type and OS image used?
