### ISSUE TITLE
Transparent Pixelstream support? (Augmented Reality / Mixed Reality)

### ISSUE THREAD

**Issue by xlgn** [EpicGames/PixelStreamingInfrastructure#298]
## Component your question relates to
- [ ] Signalling server
- [x] Frontend library
- [ ] Frontend UI library
- [ ] Matchmaker
- [ ] SFU
- [x] This repo
- [x] Other

## Question
Even if it isn't in the scope of this project: Technically, would it be possible to add transparency support to the XR Pixelstream for Augmented Reality? 

## Details
The idea is to have a greenscreen level with a few objects and do UE Pixelstreaming to a Webbrowser on the Meta Quest 3. The Pixelstream video comes with an alpha channel OR a greenscreen mask will be applied, which theoretically results in an Augmented Reality experience.

## Follow Up Questions
I did some diggin but couldn't find much information on this topic. Unreal Engine, WebXR and Meta Quest 3 Webbrowser all support transparent videos according to my research. Is there a technical reason/limitation why it hasn't been done already?

**Comment by lukehb** [comment]
Hi @xlgn!

> The idea is to have a greenscreen level with a few objects and do UE Pixelstreaming to a Webbrowser on the Meta Quest 3. The Pixelstream video comes with an alpha channel OR a greenscreen mask will be applied, which theoretically results in an Augmented Reality experience.

While it is not on our roadmap I am happy to answer.

I think it is totally possible. WebRTC video streams out of Pixel Streaming don't support alpha today, so your best bet would be a green screen level and then you could do the masking in the browser using some of the available video processing APIs the browsers have these days.

> Is there a technical reason/limitation why it hasn't been done already?

WebRTC streaming (used by Pixel Streaming) does not support for video with alpha out of the box.
