### ISSUE TITLE
Refactor Matchmaker to be consumable as an extensible library

### ISSUE THREAD

**Issue by DenisTensorWorks** [EpicGames/PixelStreamingInfrastructure#3]
We want to update the Matchmaker scripts so they can be interfaced with as a library.

This will more easily allow users to simply integrate the functionality they need from the library into their own infrastructure, along with the benefits described in the referred to issue above.

We should expose this as `lib-psmatchmaker` or potentially fold this into the SignallingWebServer lib.

---

Moved from https://github.com/EpicGames/PixelStreamingInfrastructure/issues/12

**Comment by lukehb** [comment]
Matchmaker support has been dropped in UE 5.5. Closing, Details: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/pull/160
