### ISSUE TITLE
Can I use Pixel Stream on my Intel Arc 770 graphics card

### ISSUE THREAD

**Issue by bningj** [EpicGames/PixelStreamingInfrastructure#307]
As mentioned in the question, can the pixel stream series of projects work well on Intel's Arc770, I don't know if anyone has tested it.

**Comment by lukehb** [comment]
No, unfortunately at this time Pixel Streaming does not hardware accelerated encoding using Intel GPUs. You could stream VP8/VP9 on your system but it would be using the CPU instead.

There are no plans to added support for Intel hardware accelerated encoding on our roadmap currently.
