### ISSUE TITLE
[BUG] - initial settings in uiless.ts 

### ISSUE THREAD

**Issue by nmalisa-sb** [EpicGames/PixelStreamingInfrastructure#308]
**UE Version:**
UE 5.4

**Frontend Version:**
UE 5.4

**Problem component**
Frontend, typescript implementation

**Description**
The problem is visible when Signalling server does not run locally, but on some remote server (e.g. AWS) so that URL is not `localhost` but anything else. When using UILess mode, the frontend tries to connect to `ws://localhost`, fails and streaming does not work.

**The Bug**
Setting initial value for signalling server URL in `Frontend/implementations/typescript/src/uiless.ts`, line 10:
```ts
	const config = new Config({
		initialSettings: {
			AutoPlayVideo: true,
			AutoConnect: true,
			ss: "ws://localhost:80",   // <-- this line should be removed
			StartVideoMuted: true,
			WaitForStreamer: true,
		}
	});
```
Newly added check in file `Frontend/library/src/Config/Config.ts`, line 180:
```ts
	this.textParameters.set(
            TextParameters.SignallingServerUrl,
            new SettingText(
                TextParameters.SignallingServerUrl,
                'Signalling url',
                'Url of the signalling server',
                settings && settings.hasOwnProperty(TextParameters.SignallingServerUrl) ?    // <-- this and next line
                    settings[TextParameters.SignallingServerUrl] :
                    (location.protocol === 'https:' ? 'wss://' : 'ws://') +
                        window.location.hostname +
                        // for readability, we omit the port if it's 80
                        (window.location.port === '80' ||
                        window.location.port === ''
                            ? ''
                            : `:${window.location.port}`),
                useUrlParams
            )
        );
```
Because of this combination, the value for SignallingServerUrl remains as set in initial settings..

**Steps to Reproduce:**
1. set the HomepageFile in `config.json` to "uiless.js":
```json
	"HomepageFile": "uiless.html",
```
2. run signalling server and try to open pixel streaming website
3. errors are visible in JS console (or developer tools) - the browser is trying to connect to `localhost` instead of correct server URL

**Expected behavior**
1. signalling server URL probably should not be set in initial settings

**Comment by lukehb** [comment]
@nmalisa-sb Thanks for reporting this, I made the suggested fix and have backported it across all our supported versions.
