### ISSUE TITLE
Msg: There was no registered handler for "TextboxEntry" - try adding one using registerMessageHandler(MessageDirection.ToStreamer, "TextboxEntry", myHandler)

### ISSUE THREAD

**Issue by AmbitionGan** [EpicGames/PixelStreamingInfrastructure#31]
**UE Version:**
 UE 5.2

**Frontend Version:**
 UE5.2

**Problem component**
Signalling Server, Frontend, Pixel Streaming C++ plugin

The signaling service is enabled but streaming on the web is always WebRTC connected, waiting for video; Don't come out of the picture! The following Error message is displayed: Level: Error
Msg:  There was no registered handler for "TextboxEntry" - try adding one using  registerMessageHandler(MessageDirection.ToStreamer, "TextboxEntry", myHandler)
Caller:
at i.Gestacktrace;
![问题1](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/28282611/42ef9c70-1642-4185-acfb-9e43c23d0e87)
![问题2](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/28282611/bbce159a-522a-4ef4-a6e3-7d94b3a8a490)
![问题3](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/28282611/c950e382-cf57-4880-ba60-7e33c4338195)

**Comment by Belchy06** [comment]
Hey @AmbitionGan,

Add [this ](https://github.com/EpicGames/PixelStreamingInfrastructure/pull/336/commits/bd13d348ada00b23b38ff4cd3dea78b7804f8743#diff-465c3b8149ac01cae945f0675fb822782b7f0d2812a63877be7ef7a511b6b2f8R510-R517) code to your `Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts` file.
