### ISSUE TITLE
The source code is being included twice in our packaged libraries (5.5 confirmed)

### ISSUE THREAD

**Issue by DenisTensorWorks** [EpicGames/PixelStreamingInfrastructure#321]
**Frontend version**
5.5, possibly earlier as well

**Problem component**
Frontend

**Description**
The source code is being included twice in our packaged libraries, which is causing a larger download size than necessary, longer compile times, more convulted builds, more difficult debugs, and tricky bugs when/if users use the wrong functions.

**Comment by lukehb** [comment]
I'm unsure if this is true for version prior to 5.5, but I will prepare a fix and backport as necessary.

**Comment by lukehb** [comment]
Fixed in master and UE5.5 branches: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/commit/a7e4a3eec4f760783c7f19f4b93a3154ca335d08
