### ISSUE TITLE
After configuring AutoPlayVideo, the playback button is still displayed on the screen

### ISSUE THREAD

**Issue by xingxiang1227** [EpicGames/PixelStreamingInfrastructure#33]
**UE Version:**
E.g. UE 5.2

**Frontend Version:**
E.g. UE5.2.1

**Problem component**
```javascript
import { Config, PixelStreaming } from "@epicgames-ps/lib-pixelstreamingfrontend-ue5.2";
const config = new Config({
    useUrlParams: false,
    initialSettings: {
        ss: 'ws://localhost:8081',
        AutoConnect: true,
        AutoPlayVideo: true
    }
});
```

**Description**
After configuring AutoPlayVideo, the playback button is still displayed on the screen，Or could you please tell me how to use the method to initialize autoplay for the video? Thank you very much.

**Screenshots**
![1710407245630](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/20619652/1ca816ef-67d5-440e-aad2-961b1e08bb16)

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10 Pro]
 - Browser + version [e.g. chrome 122]

**Comment by timbotimbo** [comment]
Can you try using `StartVideoMuted: true` ?
Browsers won't let a video autoplay if it contains audio.

**Comment by xingxiang1227** [comment]
> Can you try using `StartVideoMuted: true` ? Browsers won't let a video autoplay if it contains audio.

After trying to set `StartVideoMuted: true`, the video still cannot be played automatically.
```javascript
const config = new Config({
    useUrlParams: false,
    initialSettings: {
        ss: 'ws://127.0.0.1:91',
        AutoConnect: true,
        AutoPlayVideo: true,
        StartVideoMuted: true
    }
});
```

**Comment by AmbitionGan** [comment]
开启信令服务了吗

**Comment by AmbitionGan** [comment]
你确定你这个是通的吗 ss: 'ws://localhost:8081',

**Comment by xingxiang1227** [comment]
> 你确定你这个是通的吗 ss: 'ws://localhost:8081',

信令服务开启了，画面会出现播放按钮，我点击后可以正常看到画面

**Comment by xingxiang1227** [comment]
### UE5 Packaging Page
I use UE5 packaged pages to access, UrlParams settings `AutoConnect：true, AutoPlayVideo: true, StartVideoMuted: true`, and the screen can automatically play。
![1710467293619](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/20619652/676fb6f0-f0ee-4fcf-a61c-812b81b7ed67)

![1710467325132](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/20619652/cc88ad0d-f4ca-4088-ba46-ba2b123129c4)

### VUE Packaging Page
```javascript
import { Config,PixelStreaming} from "@epicgames-ps/lib-pixelstreamingfrontend-ue5.2";
import {Application,PixelStreamingApplicationStyle} from "@epicgames-ps/lib-pixelstreamingfrontend-ui-ue5.2";
const PixelStreamingApplicationStyles = new PixelStreamingApplicationStyle();
PixelStreamingApplicationStyles.applyStyleSheet();

const config = new Config({
    useUrlParams: true,
    initialSettings: {
        ss: 'ws://127.0.0.1:91',
        AutoConnect: true,
        AutoPlayVideo: true,
        StartVideoMuted: true
    }
});

// Create a Native DOM delegate instance that implements the Delegate interface class
stream = new PixelStreaming(config);
const application = new Application({
    stream,
    onColorModeChanged: (isLightMode) =>
        PixelStreamingApplicationStyles.setColorMode(isLightMode),
});

document.body.appendChild(application.rootElement);
```

![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/20619652/64a96495-7d34-458c-932e-37f909bd44a0)

**Comment by AmbitionGan** [comment]
可以加你好友讨论一下吗 我做的也是vue和ue

**Comment by xingxiang1227** [comment]
> 可以加你好友讨论一下吗 我做的也是vue和ue

联系方式可以发下邮箱791301433@qq.com

**Comment by xingxiang1227** [comment]
qq:791310433，麻烦添加一下，像大佬请教下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EpicGamesExt/PixelStreamingInfrastructure"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月18日(星期一) 下午5:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EpicGamesExt/PixelStreamingInfrastructure] After configuring AutoPlayVideo, the playback button is still displayed on the screen (Issue #33)





 
可以加你好友讨论一下吗

**Comment by AmbitionGan** [comment]
> 791310433
好了 加了

**Comment by lukehb** [comment]
@xingxiang1227 Am I understanding correctly, if you set the parameters in code it won't autoplay, but if you set them in the browser using the settings panel then it will play automatically?

**Comment by xingxiang1227** [comment]
> @xingxiang1227 Am I understanding correctly, if you set the parameters in code it won't autoplay, but if you set them in the browser using the settings panel then it will play automatically?

The page packaged using the UE5 engine can autoplay through the settings panel, but the Vue page I wrote myself, after integrating pixel streaming, cannot achieve autoplay. Is it because my settings are incorrect?
