### ISSUE TITLE
 PixelStreamin  Enlarge Display to Fill Window

### ISSUE THREAD

**Issue by lingGuanX** [EpicGames/PixelStreamingInfrastructure#331]
## Component your question relates to
- [ ] Signalling server
- [x] Frontend library
- [ ] Frontend UI library
- [ ] Matchmaker
- [ ] SFU
- [ ] This repo
- [ ] Other

## Background
I tried using PixelStreaming in UE5.3,The displayed window size does not fill my browser page,I found out that 'Enlarge Display to Fill Window ' might be able to help me. However, this option is not available in the documentation from 5.2 onwards.

## Question
How do I fix this in UE5.3 or Or where to find this option

## Additional context
Add any other context or screenshots that are relevant for your question.

**Comment by lukehb** [comment]
I think what you want is the Match viewport resolution option ([see here](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/blob/master/Frontend/Docs/Settings%20Panel.md))

Three ways to set this:

1. Using the UI click the match viewport resolution toggle
2. Adding a url parameter
3. Setting it in code.

The url parameter is activated by appending `?MatchViewportRes=true` to the end of the url, so like `http://localhost/?MatchViewportRes=true`

**Comment by lukehb** [comment]
This is confirmed working in the latest UE 5.5 btw.
