### ISSUE TITLE
TypeScript compiler options

### ISSUE THREAD

**Issue by dan-tw** [EpicGames/PixelStreamingInfrastructure#351]
**Component your feature request relates to**
- [x] Signalling server
- [x] Frontend library
- [x] Frontend UI library

**Problem your feature solves? Please describe.**
The Pixel Streaming Infrastructure is currently not compatible with projects that have strict TypeScript compiler options configured

**Describe the solution you'd like**
Enabling the following TypeScript compiler options for PSInfra:

- [forceConsistentCasingInFileNames](https://www.typescriptlang.org/tsconfig/#forceConsistentCasingInFileNames)
- [strict](https://www.typescriptlang.org/tsconfig/#strict)
- [noImplicitOverride](https://www.typescriptlang.org/tsconfig/#noImplicitOverride)
- [noFallthroughCasesInSwitch](https://www.typescriptlang.org/tsconfig/#noFallthroughCasesInSwitch)
- [noImplicitReturns](https://www.typescriptlang.org/tsconfig/#noImplicitReturns)
- [noPropertyAccessFromIndexSignature](https://www.typescriptlang.org/tsconfig/#noPropertyAccessFromIndexSignature)

I think they will help improve code quality, consistency and most importantly compatibility (e.g. it will work with other projects that are strict).

**Additional context**
-

**Comment by lukehb** [comment]
If backporting is painful feel free to skip it in this case.
