### ISSUE TITLE
[BUG] - https://github.com/EpicGamesExt/PixelStreamingInfrastructure/releases/download/v4.5.2-coturn-windows/turnserver.zip is 404

### ISSUE THREAD

**Issue by lukas-kyeso** [EpicGames/PixelStreamingInfrastructure#36]
**UE Version:**
E.g. UE 5.4

**Frontend Version:**
E.g. UE5.4

**Problem component**
setup_coturn.bat

**Description**
setup_coturn.bat in the 5.4-0.0.5 tries to download coturn from:
https://github.com/EpicGamesExt/PixelStreamingInfrastructure/releases/download/v4.5.2-coturn-windows/turnserver.zip
which returns a 404

**Steps to Reproduce:**

**Expected behavior**
The should exist or the url should be updated

**Comment by lukehb** [comment]
Should be fixed now as per: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/pull/47#issuecomment-2030994836
