### ISSUE TITLE
Container images/docker files SFU

### ISSUE THREAD

**Issue by DenisTensorWorks** [EpicGames/PixelStreamingInfrastructure#4]
We currently provide scripts which will install all the required dependencies and run each of the SignallingWebServer, SFU, or Matchmaker. This works pretty well but still involves machinery with the potential to fail in not accounted for environments.

We can sidestep these difficulties by additionally providing a mechanism to build these individual applications as a standalone executable using a technology such as https://github.com/nexe/nexe

---

Moved from https://github.com/EpicGames/PixelStreamingInfrastructure/issues/13

**Comment by lukehb** [comment]
Container images for SFU are at: https://hub.docker.com/r/pixelstreamingunofficial/pixel-streaming-sfu/tags
