### ISSUE TITLE
Documentation around the "UseFrontend" config in the SignallingServer

### ISSUE THREAD

**Issue by rotor-antoine** [EpicGames/PixelStreamingInfrastructure#45]
The UseFrontend config of the SignallingServer seems to enable some web requests to frontend endpoints, but I can't find any trace of those endpoint implementation in the frontend samples. 
It feels like this config deserve at least more documentation and maybe:
- a frontend sample
- or just be removed from the signalling server. I doubt many people are using it in it's current state.

**Comment by rotor-antoine** [comment]
It could also use a more meaning full name. UseFrontend seems a bit too generic for what it does.

**Comment by lukehb** [comment]
That was a legacy option that existed before 4.27, it is no longer has any function, and is removed in the 5.5 branch.

I would strongly advise you to not build functionality on top of it.
