### ISSUE TITLE
[BUG] - PixelStreaming FrontEnd Starts to Drop All Frames

### ISSUE THREAD

**Issue by TxMat** [EpicGames/PixelStreamingInfrastructure#49]
**UE Version:**
UE 5.3.0 (from source with modified VideoEncoder.h as stated in the previous repo to avoid crash)

**Frontend Version:**
Latest UE 5.3.0 version from this repo

**Problem component**
Pixel Streaming Frontend

**Description**
When in pixel streaming after a few seconds the front end seems to start dropping all the frames despite the backend still encoding and sending them.

**Steps to Reproduce:**
- Launch a pixel streaming instance with matchmaker, renderoffscreen and signaling with turn server
- play for 5minutes 

Interestingly the inputs are still being sent it's only the rendering that is not working.

**Expected behavior**
- Launch a pixel streaming instance with matchmaker, renderoffscreen and signaling with turn server
- play forever

**Screenshots**
Task Manager :
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/46858765/5eed087f-4ab1-4376-bdb3-721314a27e84)
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/46858765/94427bc1-4c87-4815-be11-23ba9eb7c71b)
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/46858765/b2f45094-2d93-4475-b236-be67f6a16eeb)

**Platform (please complete the following information):**
 - OS: [Windows Server 2022 Datacenter, 21H2, 20348.2322]
 - Browser + version [latest edge version]

**Additional context**
the modified line in VideoEncoder.h is :
```c++
// file : Engine/Plugins/Experimental/AVCodecs/AVCodecsCore/Source/AVCodecsCore/Public/Video/VideoEncoder.h line 154
TSharedPtr<TChildResource> MappedResource = Resource->template PinMapping<TChildResource>()
```

**Comment by TxMat** [comment]
More details due to troubleshooting today, it seems that the frontend starts dropping all the frames and never recovers
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/46858765/e15e6af0-b573-4f34-9e67-6e44e71b7421)

**Comment by lukehb** [comment]
Hi @TxMat I would kindly ask you to share some extra info if you can:

1. Can you share the UE log from your application when this happens?
2. Does this happen in UE 5.4 preview?
3. Can you reproduce the issue without matchmaker/TURN?
4. Can you reproduce the issue on your local machine?

**Comment by TxMat** [comment]
Hi, thanks for the quick follow up :

1. [here](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/files/14914937/LOG_08_04.txt) it is but it seems that nothing is being written to the log that's useful 
2. I didn't tried in 5.4
3. Yes, TURN and MM are unrelated to the issue
4. No, it consistently works on localhost.
5. Bonus, the modifiers i use when launching the game : -log -AudioMixer -PixelStreamingIP=localhost -PixelStreamingPort=8888 -RenderOffScreen

Oddly enough in a vain attempt to fix the problem i've recreated a fresh new machine on AWS, loaded the same version of the game and the same pixel streaming infrastructure and the bug does not seems to occurs anymore. 

I'll keep you updated next week if the bug comes back

**Comment by lukehb** [comment]
On AWS are you using g4dn? Just trying to match the environment.

**Comment by lukehb** [comment]
Lemme know if you can reproduce.

**Comment by TxMat** [comment]
> On AWS are you using g4dn? Just trying to match the environment.

Yes we are indeed using G4DNs

**Comment by lukehb** [comment]
Any luck reproducing?

**Comment by TxMat** [comment]
Sorry I got moved to another project this week, I'll update you on Monday.

**Comment by TxMat** [comment]
Cannot reproduce. i'll reopen is issue if the bug shows up again
