### ISSUE TITLE
pixel streaming is stuck when running at greater than 4k resolution

### ISSUE THREAD

**Issue by 0wendy0** [EpicGames/PixelStreamingInfrastructure#50]
## Component your question relates to
- [x] Signalling server
- [x] Frontend library
- [x] Frontend UI library
- [ ] Matchmaker
- [ ] SFU
- [ ] This repo
- [ ] Other

## Background
When my game screen is at 4k resolution, pixel streaming is available, but when I set the game screen to 5k resolution, pixel streaming is stuck, and the frontend information shows "webrtc connected, waiting for video"

## Question
Is there any way I can set the game screen to be 5k, but the pixel streaming screen to be 1k?

## Additional context
![image](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/38154350/4f5c7b65-e4d6-4b2d-a76a-fe7a70f90172)

**Comment by MWillWallT** [comment]
Hi there!

Unfortunately, there isn't anything out of the box to separate the game/application resolution and the stream resolution. They are tied together by default.

However, if you're comfortable changing C++, the `FinalScale` parameter could be set to some multiplier in `Engine\Plugins\Media\PixelStreaming\Source\PixelStreaming\Private\PixelStreamingVideoInputRHI.cpp`

**Comment by lukehb** [comment]
Extra bit of info:

Pixel Streaming has a maximum for 4096x4096 encoding resolution. 5k encoding is not supported on enough GPUs yet, so that is why the stream cannot connect - the frame cannot be encoded.
