### ISSUE TITLE
Add URL checker to GitHub actions

### ISSUE THREAD

**Issue by DenisTensorWorks** [EpicGames/PixelStreamingInfrastructure#8]
In order to prevent doc rot, we should implement a URL checker to an action that looks in .md files for broken links.

---

Moved from https://github.com/EpicGames/PixelStreamingInfrastructure/issues/249

**Comment by lukehb** [comment]
This looks like a good action to get it done:

https://github.com/marketplace/actions/markdown-link-check

Example usage: https://geoffhudik.com/tech/2020/10/05/automate-checking-markdown-links-with-github-actions/
