### ISSUE TITLE
Get player id in  UIInteraction

### ISSUE THREAD

**Issue by ibreathebsb** [EpicGames/PixelStreamingInfrastructure#83]
## Component your question relates to
- [x] Signalling server
- [x] Frontend library
- [ ] Frontend UI library
- [ ] Matchmaker
- [ ] SFU
- [ ] This repo
- [ ] Other

## Question
I'd like to implement a system where a user  acts as controller while others act as viewer,I see Signalling server defines player id,how can we get player id in frontend so that I can send it in UIInteraction,or is there a way to get message's sender in Unreal, Thanks!

**Comment by lukehb** [comment]
If the ultimate goal is one user is the controller and the others are viewers, I think you might want to study using the [SFU](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/tree/master/SFU) for the viewers and the controlling peer being not connected to the SFU. And then you may wish to launch Pixel Streaming with `-PixelStreamingInputController=host` which will allow only the directly connected peer to be control the input.
